class DimensionError(Exception):
    pass


def error(message):
    print('ERROR')
    print(message)
    print('ERROR')
